# Generated by Django 5.2.6 on 2025-11-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.AddField(
            model_name='banner',
            name='linked_product',
            field=models.ForeignKey(blank=True, help_text='选择一个商品', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='跳转商品'),
        ),
        migrations.AddField(
            model_name='banner',
            name='linked_shop',
            field=models.ForeignKey(blank=True, help_text='选择一个店铺，将优先于商品链接', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='跳转店铺'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='默认标题', help_text='仅用于后台识别', max_length=100, verbose_name='横幅标题'),
        ),
    ]
