# Generated by Django 5.2.6 on 2025-11-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_banner_link_banner_linked_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='优惠金额'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='优惠码')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='抵扣金额')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='最低消费金额')),
                ('valid_from', models.DateTimeField(verbose_name='生效时间')),
                ('valid_to', models.DateTimeField(verbose_name='失效时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='shop.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.coupon', verbose_name='使用的优惠券'),
        ),
    ]
