# Generated by Django 5.2.6 on 2025-11-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_discount_coupon_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='平均评分'),
        ),
        migrations.AddField(
            model_name='shop',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='评分总数'),
        ),
    ]
